#index:
#    path: /
#    controller: App\Controller\DefaultController::index

pro_stage_accueil:
    path: /
    controller: App\Controller\ProStageController::indexAccueil

pro_stage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::indexEntreprises

pro_stage_formations:
    path: /formation
    controller: App\Controller\ProStageController::indexFormations

pro_stage_stages:
    path: /stages/{id}
    controller: App\Controller\ProStageController::indexStages

pro_stage_stages_par_nom_entreprise:
    path: /entreprises/{nomEntreprise}
    controller: App\Controller\ProStageController::indexStagesParNomEntreprise

pro_stage_stages_par_formation:
    path: /formation/{nomCourt}
    controller: App\Controller\ProStageController::indexStagesParFormation

pro_stage_ajout_entreprise:
    path: /admin/entreprise/add
    controller: App\Controller\ProStageController::indexAjoutEntreprise

pro_stage_modification_entreprise:
    path: /entreprise/modify/{id}
    controller: App\Controller\ProStageController::indexModifEntreprise

pro_stage_ajout_stage:
    path: /stage/add
    controller: App\Controller\ProStageController::indexAjoutStage

pro_stage_modification_stage:
    path: /stage/modify/{id}
    controller: App\Controller\ProStageController::indexModifStage

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\SecurityController::register